"""empty message

Revision ID: 56988fc4443f
Revises: 0396de756b5e
Create Date: 2021-07-08 18:20:33.729116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56988fc4443f'
down_revision = '0396de756b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Artist', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('Show', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Show', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('Venue', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Venue', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'updated_at')
    op.drop_column('Venue', 'created_at')
    op.drop_column('Show', 'updated_at')
    op.drop_column('Show', 'created_at')
    op.drop_column('Artist', 'updated_at')
    op.drop_column('Artist', 'created_at')
    # ### end Alembic commands ###
